services:
  api:
    build: api
    ports:
      - "80:80"
    depends_on:
      - nginx

  calculator:
    build: calculator
    expose:
      - "81"
    deploy:
      mode: replicated
      replicas: 2

  nginx:
      build: nginx
      ports:
          - 8080:8080
      depends_on:
          - calculator

