version: '3'

services:
    redis-master:
        image: redis:3
        command: redis-server --save 20 1 --loglevel warning
        volumes:
          - ./data:/data

    redis-slave-1:
        image: redis:3
        command: redis-server --slaveof redis-master 6379 --save 20 1
        links:
            - redis-master

    redis-slave-2:
        image: redis:3
        command: redis-server --slaveof redis-master 6379 --save 20 1
        links:
            - redis-master

    sentinel-1:
        build: sentinel
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=500
            - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2

    sentinel-2:
        build: sentinel
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=500
            - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2

    sentinel-3:
        build: sentinel
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=500
            - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2

    redis_cluster_app:
        build: app
        ports:
          - 80:80
        environment:
          - SENTINEL_DOWN_AFTER=5000
          - SENTINEL_FAILOVER=500
          - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
        volumes:
            - ./app:/usr/src/app/redis_app/