version: '3.8'

services:
  redis-node-1:
    image: redis:7.2
    command: redis-server /redis-conf/7000.conf
    ports:
      - "7000:7000"
    volumes:
      - ./conf:/redis-conf
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.2

  redis-node-2:
    image: redis:7.2
    command: redis-server /redis-conf/7001.conf
    ports:
      - "7001:7001"
    volumes:
      - ./conf:/redis-conf
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.3

  redis-node-3:
    image: redis:7.2
    command: redis-server /redis-conf/7002.conf
    ports:
      - "7002:7002"
    volumes:
      - ./conf:/redis-conf
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.4

  redis-node-4:
    image: redis:7.2
    command: redis-server /redis-conf/7003.conf
    ports:
      - "7003:7003"
    volumes:
      - ./conf:/redis-conf
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.6

  redis-cluster-init:
    image: redis:7.2
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    entrypoint: sh -c "sleep 15 && echo yes | redis-cli --cluster create 172.28.0.2:7000 172.28.0.3:7001 172.28.0.4:7002 --cluster-replicas 0"
    networks:
      redis-cluster:

  redis_cluster_app:
    build: app
    ports:
      - 80:80
    depends_on:
        - redis-node-1
        - redis-node-2
        - redis-node-3
    volumes:
        - ./app:/usr/src/app/redis_app/
    networks:
          redis-cluster:

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

# redis-cli cluster add 172.28.0.6:7003